### PR TITLE
Fix for changes in IDE templates

### PR DESCRIPTION
**Pull request by jclariviere**
See https://github.com/ArcBees/IDE-Templates/pull/62

### CODE REVIEW

**Comment by olafleur** [comment]
Should pass when the new IDE-templates is deployed. @meriouma Is it automatic or we have to do it manually?

**Comment by meriouma** [comment]
Manually at the moment

**Comment by meriouma** [comment]
LGTM

**Comment by olafleur** [comment]
@meriouma I merged the modifications in IDE-Template. Can you deploy these changes to see if this pull request pass?

**Pull request merged**
