### PR TITLE
Add doc on how to develop the plugin and a little bit of cleanup

### PR DESCRIPTION
**Pull request by olafleur**
After some experiments this week-end, a little bit of cleanup and add some documentation to facilitate the job of someone who would like to work on the IntelliJ plugin.

### CODE REVIEW

**Comment by christiangoudreau** [comment]
LGTM

Is the updated plugin working?

**Comment by olafleur** [comment]
It's working in debug, but not in production. I'm trying to figure that out.

**Comment by olafleur** [comment]
Now working, I was installing it the wrong way.

**Comment by branflake2267** [comment]
Nice job

**Pull request merged**
